language: c

sudo: false

matrix:
  include:
    # Unrestricted
    - env: CABALVER=1.24 GHCVER=8.2.1
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.1], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    # Constrained
    - env: CABALVER=1.24 GHCVER=8.2.1 CABALCONFIG=servant-0.11
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.1], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2 CABALCONFIG=servant-0.11
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2 CABALCONFIG=servant-0.8
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3 CABALCONFIG=servant-0.7
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3 CABALCONFIG=servant-0.6
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3 CABALCONFIG=servant-0.5
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    # HEAD
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  allow_failures:
    - env: CABALVER=head GHCVER=head

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - if [ ! -z "$CABALCONFIG" ]; then cp .travis/${CABALCONFIG}-cabal.config cabal.config; fi
 - cabal install --only-dependencies --enable-tests --max-backjumps=-1
 - cabal install -v --avoid-reinstalls servant-blaze hspec-wai --constraint='foundation < 0.0.5'

script:
 - cabal configure --enable-tests --enable-library-coverage -v2 -f dev -f build-examples
 - cabal build
 - cabal test --show-details=always
 - cabal sdist
 - cabal haddock | grep "100%" | wc -l | grep "1"

# after_script:
#  - cabal install hpc-coveralls
#  - export PATH=~/.cabal/bin:$PATH
#  - hpc-coveralls --coverage-mode=StrictlyFullLines
#                  --exclude-dir=tests
#                  tests

branches:
  only:
  - master
  - lts

notifications:
  email:
    recipients:
      - zohl@fmap.me
